{
 "title": "expensy2",
 "description": "Dashboard of Keycloak metrics exported with Keycloak Metrics SPI\r\n\r\nhttps://github.com/aerogear/keycloak-metrics-spi",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(keycloak_logins,kubernetes_pod_name)"
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": "label_values(keycloak_logins{provider=\"keycloak\"},realm)"
   },
   {
    "name": "ClientId",
    "label": "ClientId",
    "query": "label_values(keycloak_logins{provider=\"keycloak\",realm=\"$realm\"},client_id)"
   }
  ]
 },
 "panels": [
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Working Memory usage (Allocatable)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 1.86",
     "legendFormat": "{{error}}"
    }
   ]
  },
  { "title": "App Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Mongodb connections",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mongo_connection_status" }
   ]
  },
  {
   "title": "HTTP requests by code",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (statusCode) (http_requests_total)",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "HTTP requests by method",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (http_requests_total)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "HTTP requests by route",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (route) (http_requests_total{route=~\"/api/expenses|/metrics\"})",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Total expenses",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "expenses_total", "legendFormat": "{{realm}}" }
   ]
  },
  {
   "title": "HTTP total requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "http_requests_overall_total" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "Comitted"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}