apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: expensy
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'expensy-backend'
        static_configs:
          - targets: ['backend:8706']
        metrics_path: '/metrics'
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: expensy
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true