apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expensy-ingress
  namespace: expensy
  annotations:
    # This links to the ClusterIssuer created by the script
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # This ensures that if someone visits the URL via HTTP, they get moved to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - expensy-lara.westeurope.cloudapp.azure.com
    secretName: expensy-tls-secret
  rules:
  # --- RULE 1: The Domain Name (with SSL) ---
  - host: expensy-lara.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8706
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8706
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
  # --- RULE 2: The Fallback (Keeps your IP working) ---
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8706
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8706
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
 